version: '3.3'
services:
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: webserver
    restart: unless-stopped
    network_mode: host