name: Dastardly Scan Action

on:
  push:
    branches:
      - feature/149-dastardly-actions

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t Dockerfile .

      - name: Run Dastardly Scan
        run: docker run --rm \
             -e DASTARDLY_TARGET_URL="https://demo.staging.tonomy.foundation" \
             -e DASTARDLY_OUTPUT_FILE="dastardly-report.xml" \
             -v ${{ github.workspace }}:/github/workspace \
             Dockerfile

      - name: Upload Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: dastardly-scan-report
          path: dastardly-report.xml
