name: Dastardly Scan Action

on:
  push:
    branches:
      - feature/149-dastardly-actions

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Dastardly Scan
        env:
          DASTARDLY_TARGET_URL: https://demo.staging.tonomy.foundation
          DASTARDLY_OUTPUT_FILE: dastardly-report.xml
        run: |
          docker run --rm \
            -e DASTARDLY_TARGET_URL \
            -e DASTARDLY_OUTPUT_FILE \
            -v ${{ github.workspace }}:/github/workspace \
            some-dastardly-image-name

      - name: Upload Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: dastardly-scan-report
          path: dastardly-report.xml
