name: Security Scan

on:
  pull_request:
    branches-ignore:
      - master

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Build app
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn run build

      - name: 🚀 Run accounts website
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: corepack enable
      - run: node generate-sitemap.js accounts
      - run: yarn run start:prod:accounts &
      - run: sleep 8

      - name: Run Dastardly scan on accounts website
        run: docker run
          --add-host host.docker.internal:host-gateway
          -e DASTARDLY_TARGET_URL=http://host.docker.internal:3000
          -e DASTARDLY_OUTPUT_FILE=/dastardly/accounts.dastardly-report.xml
          -u root
          -v $(pwd):/dastardly
          public.ecr.aws/portswigger/dastardly:latest
          dastardly

      - name: 🚀 Run demo website
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: corepack enable
      - run: node generate-sitemap.js demo
      - run: yarn run start:prod:demo &
      - run: sleep 8

      - name: Run Dastardly scan on demo website
        run: docker run
          --add-host host.docker.internal:host-gateway
          -e DASTARDLY_TARGET_URL=http://host.docker.internal:3001
          -e DASTARDLY_OUTPUT_FILE=/dastardly/demo.dastardly-report.xml
          -u root
          -v $(pwd):/dastardly public.ecr.aws/portswigger/dastardly:latest
          dastardly

      - name: Upload Scan Output
        uses: actions/upload-artifact@v3
        with:
          name: dastardly-scan-output
          path: "*dastardly-report.xml"
