name: Dastardly Scan Action

on:
  push:
    branches:
      - feature/149-dastardly-actions

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Build and run app
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: corepack enable
      - run: node src/generate-sitemap.js
      - run: yarn install --immutable
      - run: yarn run build
      - run: yarn run start:prod &
      - run: sleep 8

      - name: Run Dastardly scan on accounts website
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: curl http://accounts.localhost:5147
      - run: docker run --add-host host.docker.internal:host-gateway -e DASTARDLY_TARGET_URL=http://host.docker.internal:5147 -e DASTARDLY_OUTPUT_FILE=/dastardly/accounts.dastardly-report.xml -u root -v $(pwd):/dastardly public.ecr.aws/portswigger/dastardly:latest dastardly

      - name: Upload Scan Output
        uses: actions/upload-artifact@v3
        with:
          name: dastardly-scan-output
          path: "*dastardly-report.xml"
