name: Dastardly Scan Action

on:
  push:
    branches:
      - feature/149-dastardly-actions

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t dastardly-image .

      - name: Set Target URL
        id: set-target-url
         run: |
          if [[ ${GITHUB_REF#refs/*/} == "development" ]]; then
            target_url="https://demo.staging.tonomy.foundation/sitemap.xml"
          elif [[ ${GITHUB_REF#refs/*/} == "master" ]]; then
            target_url="https://demo.demo.tonomy.foundation/sitemap.xml"
          else
            target_url="http://demo.localhost:5147"
          fi
          echo "::set-output name=target_url::$target_url"

      - name: Extract URLs from sitemap.xml
        id: extract-urls
        run: |
          # Extract URLs from sitemap.xml and store them in a file
          target_url=${{ steps.set-target-url.outputs.target_url }}
          curl -s "$target_url" | grep -o '<loc>[^<]*</loc>' | sed 

      - name: Run Dastardly Scan and Capture Output
        id: run-scan
        run: |
          # Iterate through each URL and run Dastardly scan
          while IFS= read -r url; do
            docker run --rm \
              -e DASTARDLY_TARGET_URL="$url" \
              -e DASTARDLY_OUTPUT_FILE="/dastardly-report.xml" \
              -v ${{ github.workspace }}:/github/workspace dastardly-image \
              >> scan-output.xml 2>&1
          done < urls.txt

      - name: Upload Scan Output
        uses: actions/upload-artifact@v3
        with:
          name: dastardly-scan-output
          path: scan-output.xml
