name: Dastardly Scan Action

on:
  push:
    branches:
      - feature/149-dastardly-actions

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Dastardly Scan
        runs:
          using: 'docker'
          image: 'Dockerfile'
        env:
          DASTARDLY_TARGET_URL: https://demo.staging.tonomy.foundation
          DASTARDLY_OUTPUT_FILE: dastardly-report.xml
      - name: Upload Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: dastardly-scan-report
          path: dastardly-report.xml
