name: Run Security Scan with Dastardly and ZAP Full Scan

on:
  pull_request:
    branches-ignore:
      - master

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Build app
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn run build
      - run: echo $(id -u) $(id -g) $(whoami)

      - name: 🚀 Run accounts website
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: corepack enable
      - run: node generate-sitemap.js accounts
      - run: yarn run start:prod:accounts &
      - run: sleep 8

      - name: Run ZAP Full Scan on the accounts website
        id: zap_scan
        # https://www.zaproxy.org/docs/docker/full-scan/
        run: |
          set +e        
          docker run \
          --add-host host.docker.internal:host-gateway \
          -v $(pwd):/zap/wrk/:rw \
          -u root \
          -t \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-full-scan.py \
          -t http://host.docker.internal:3000 \
          -j \
          -g gen.conf \
          -r accounts.zap-scan-report.html \
          -a
          echo "ZAP_ACCOUNTS_EXIT_CODE=$?" >> $GITHUB_OUTPUT

      - name: Run Dastardly scan on accounts website
        # https://portswigger.net/burp/documentation/dastardly/generic
        run: docker run
          --add-host host.docker.internal:host-gateway
          -e DASTARDLY_TARGET_URL=http://host.docker.internal:3000
          -e DASTARDLY_OUTPUT_FILE=/dastardly/accounts.dastardly-report.xml
          -u root
          -v $(pwd):/dastardly
          public.ecr.aws/portswigger/dastardly:latest
          dastardly
          echo $? > dastardly_accounts_exit_code.txt
          # echo "DASTARDLY_ACCOUNTS_EXIT_CODE=$?" >> $GITHUB_ENV


      - name: 🚀 Run demo website
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: corepack enable
      - run: node generate-sitemap.js demo
      - run: yarn run start:prod:demo &
      - run: sleep 8

      - name: Run Dastardly scan on demo website
        run: docker run
          --add-host host.docker.internal:host-gateway
          -e DASTARDLY_TARGET_URL=http://host.docker.internal:3001
          -e DASTARDLY_OUTPUT_FILE=/dastardly/demo.dastardly-report.xml
          -u root
          -v $(pwd):/dastardly public.ecr.aws/portswigger/dastardly:latest
          dastardly
          echo $? > dastardly_demo_exit_code.txt

      - name: Run ZAP Full Scan on the demo website
        # https://www.zaproxy.org/docs/docker/full-scan/
        run: |
          set +e       
          docker run \
          --add-host host.docker.internal:host-gateway \
          -v $(pwd):/zap/wrk/:rw \
          -t \
          -u root \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-full-scan.py \
          -t http://host.docker.internal:3001 \
          -j \
          -g gen.conf \
          -r demo.zap-scan-report.html \
          -a
          echo "ZAP_DEMO_EXIT_CODE=$?" >> $GITHUB_OUTPUT
          
      - name: Upload ZAP Scan Output
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-output
          path: "*zap-scan-report.html"
  
      - name: Convert Accounts Dastardly JUnit XML report to HTML
        uses: pl-strflt/junit-xml-to-html@v1
        with:
          mode: 'no-frames'
          input: 'accounts.dastardly-report.xml'
          output: 'accounts.dastardly-report.html'

      - name: Convert Demo Dastardly JUnit XML report to HTML
        uses: pl-strflt/junit-xml-to-html@v1
        with:
          mode: 'no-frames'
          input: 'demo.dastardly-report.xml'
          output: 'demo.dastardly-report.html'

      - name: Upload Dastardly HTML Scan Output
        uses: actions/upload-artifact@v3
        with:
          name: dastardly-scan-output
          path: "*dastardly-report.html"

      - name: Check scan exit codes
        run: |
          if [[ -f "dastardly_accounts_exit_code.txt" && $(cat dastardly_accounts_exit_code.txt) -gt 0 ]]; then
            echo "Dastardly Scan on accounts website"
            exit $(cat dastardly_accounts_exit_code.txt)
          fi

          if [[ -f "dastardly_demo_exit_code.txt" && $(cat dastardly_demo_exit_code.txt) -gt 0 ]]; then
            echo "Dastardly Scan on demo website"
            exit $(cat dastardly_demo_exit_code.txt)
          fi

          if [[ ${{ steps.zap_scan.outputs.ZAP_ACCOUNTS_EXIT_CODE }} -gt 0 ]]; then
            echo "ZAP Scan on accounts website"
            exit ${{ steps.zap_scan.outputs.ZAP_ACCOUNTS_EXIT_CODE }}
          fi

          if [[ ${{ steps.zap_demo_scan.outputs.ZAP_DEMO_EXIT_CODE }} -gt 0 ]]; then
            echo "ZAP Scan on demo website"
            exit ${{ steps.zap_demo_scan.outputs.ZAP_DEMO_EXIT_CODE }}
          fi       

  